const Routes = {
  //All Screens
  AddCardDetails: 'AddCardDetails',
  AddNewPaypal: 'AddNewPaypal',
  AddToCartScreen: 'AddToCartScreen',
  AddressSetting: 'AddressSetting',
  ChangePassword: 'ChangePassword',
  ChatScreen: 'ChatScreen',
  CheckOutScreen: 'CheckOutScreen',
  ChooseLanguage: 'ChooseLanguage',
  CreateAccountSlideshow: 'CreateAccountSlideshow',
  DeliveryProcessScreen: 'DeliveryProcessScreen',
  DeliveryInfoScreen: 'DeliveryInfoScreen',
  LocationInfoScreen: 'LocationInfoScreen',
  PaymentMethodsSelectScreen: 'PaymentMethodsSelectScreen',
  FAQScreen: 'FAQScreen',
  FilterScreen: 'FilterScreen',
  FoodDiscover: 'FoodDiscover',
  CompareScreen: 'CompareScreen',
  InvoiceScreen: 'InvoiceScreen',
  LookingByMapScreen: 'LookingByMapScreen',
  OTPVerification: 'OTPVerification',
  OnlineSupport: 'OnlineSupport',
  Other: 'Other',
  PersonalInformation: 'PersonalInformation',
  PrivacyPolicy: 'PrivacyPolicy',
  ProductReviewScreen: 'ProductReviewScreen',
  Registration: 'Registration',
  RestaurantDescriptionScreen: 'RestaurantDescriptionScreen',
  RestaurantMenuScreen: 'RestaurantMenuScreen',
  RestaurantsListing: 'RestaurantsListing',
  Settings: 'Settings',
  ShareEarnScreen: 'ShareEarnScreen',
  SliderSelectedScreen: 'SliderSelectedScreen',
  StoreReviewScreen: 'StoreReviewScreen',
  SurrenderActScreen: 'SurrenderActScreen',
  TermsOfUse: 'TermsOfUse',
  TopCategories: 'TopCategories',
  Welcome: 'Welcome',

  //Tab Menus
  CartTabMenu: 'CartTabMenu',
  DiscoverTabMenu: 'DiscoverTabMenu',
  FavouriteTabMenu: 'FavouriteTabMenu',
  HistoryTabMenu: 'HistoryTabMenu',
  ProfileTabMenu: 'ProfileTabMenu',

  //Home Screens for Modular Menus
  CouponHomeScreen: 'CouponHomeScreen',
  FavoriteProductsHomeScreen: 'FavoriteProductsHomeScreen',
  OrderHistoryHomeScreen: 'OrderHistoryHomeScreen',
  PaymentMethodsHomeScreen: 'PaymentMethodsHomeScreen',
  ProfileHomeScreen: 'ProfileHomeScreen',
  SupportHomeScreen: 'SupportHomeScreen',

  //Module Menus
  CouponModuleMenu: 'CouponModuleMenu',
  DiscoverModuleMenu: 'DiscoverModuleMenu',
  FavoriteProductsModuleMenu: 'FavoriteProductsModuleMenu',
  OrderHistoryModuleMenu: 'OrderHistoryModuleMenu',
  OtherModuleMenu: 'OtherModuleMenu',
  PaymentMethodModuleMenu: 'PaymentMethodModuleMenu',
  ProfileModuleMenu: 'ProfileModuleMenu',
  SettingModuleMenu: 'SettingModuleMenu',
  ShareEarnModuleMenu: 'ShareEarnModuleMenu',
  SupportModuleMenu: 'SupportModuleMenu',
};

export default Routes;
